{
	"version": 1518089132,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/tiledbackground4.png",
		"images/terrainunit-sheet0.png",
		"images/terrainunit4-sheet0.png",
		"images/greenprojectile-sheet0.png",
		"images/player-sheet0.png",
		"images/collisionbox-sheet0.png",
		"images/gunarmright-sheet0.png",
		"images/platformmedium-sheet0.png",
		"images/platformsmall-sheet0.png",
		"images/platformlarge-sheet0.png",
		"images/mediumboulder-sheet0.png",
		"images/spikeballsmall-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/enemyprojectile-sheet0.png",
		"images/enemyprojectile-sheet1.png",
		"images/orangeexplosion-sheet0.png",
		"images/orangeexplosion-sheet1.png",
		"images/orangeexplosion-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"images/particles.png",
		"images/play-sheet0.png",
		"images/settings-sheet0.png",
		"images/moregames-sheet0.png",
		"images/exit-sheet0.png",
		"images/cursor-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"media/bump fx.ogg",
		"media/explode fx.ogg",
		"media/one shot laser fx.ogg",
		"media/thrust loop fx.ogg",
		"media/washyspaceguitar.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}